javafx:
  title: xx智能云打印助手 - By：LLmoe
  appicons: /icon/icon.png
  stage:
    width: 900
    height: 450
    style: DECORATED  # javafx.stage.StageStyle [DECORATED, UNDECORATED, TRANSPARENT, UTILITY, UNIFIED]
    resizable: false
socketio:
  # host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
  host: 0.0.0.0
  port: 17521
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576000
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576000
  # socket线程组大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 1
  #允许服务自定义请求不同于socket.io协议
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

spring:
  jmx:
    enabled: false

logging:
  level:
    com.llmoe: debug
